apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible-container
        image: ${ansible_image}
        volumeMounts:
        - name: ansible-config-volume
          mountPath: /etc/ansible
        command: ["/bin/sleep", "infinity"]
        resources:
          limits:
            cpu: ${cpu_limit}
            memory: ${memory_limit}
  volumeClaimTemplates:
  - metadata:
      name: ansible-config-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: ${storage_request}