apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-config
data:
  ansible.cfg: |
    [defaults]
    inventory = /etc/ansible/hosts
    remote_user = {{ remote_user }}
    private_key_file = {{ private_key_file }}