---
- name: Configure RHEL Instance
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - variables.yml

  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 60
        timeout: 300

    - name: Add instance to host group
      add_host:
        name: "{{rhel_host}}"
        ansible_host: "{{ ansible_host }}"
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ssh_private_key_file}}"
    
