---
- name: Install IDM
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - variables.yml

  tasks:
    - name: Register the system with Red Hat Subscription Manager
      ansible.builtin.command: >
        subscription-manager register
        --username "{{ username }}"
        --password "{{ password }}"
      when: username is defined and password is defined
      changed_when: false

    - name: Attach the system to the appropriate subscription
      ansible.builtin.command: subscription-manager attach --auto
      when: username is defined and password is defined
      changed_when: false

    - name: Enable the required repositories
      ansible.builtin.command: >
        subscription-manager repos
        --enable rhel-8-for-x86_64-baseos-rpms
        --enable rhel-8-for-x86_64-appstream-rpms
        --enable rhel-8-for-x86_64-highavailability-rpms
      when: username is defined and password is defined
      changed_when: false

    - name: Install IDM packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - ipa-server
        - ipa-server-dns
        - bind-utils

    - name: Setup IDM Server
      ansible.builtin.command: >
        ipa-server-install
        --domain="{{ domain }}"
        --realm="{{ realm }}"
        --ds-password="{{ ds_password }}"
        --admin-password="{{ admin_password }}"
        --setup-dns
        --auto-forwarders
        --auto-reverse
        --unattended
      when: domain is defined and realm is defined and ds_password is defined and admin_password is defined
      changed_when: false

    - name: Open Firewall Ports
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
        - ldap
        - ldaps
        - kerberos
        - dns

    - name: Reload Firewall
      ansible.posix.firewalld:
        state: reloaded